### ISSUE TITLE
Is this like usability testing?

### ISSUE THREAD

**Issue by franziskaheine** [jdittrich/userNeedResearchBook#23]
The methods I will demonstrate here can be applied if you have a product but also if you only have rough ideas about an area you are interested in designing for.

- I think what you actually do when writing a book is describing things... demonstrating is more connected to actually actively showing something.

**Comment by franziskaheine** [comment]
This allows us to explore the actual actions and the reasons behind them – because even if you might be puzzled about some things you observe they usually make perfect sense for the users.

- "actual actions" somehow sounds off... I know what you are trying to say but maybe it works better with "This allows us to observe/understand/... the user actions and the reasons behind them - even if you might be puzzled about some things you see, they usually make perfect sense for the user."

**Comment by jdittrich** [comment]
I reworked the intro section
