### ISSUE TITLE
Couldn't I just ask what they want?

### ISSUE THREAD

**Issue by franziskaheine** [jdittrich/userNeedResearchBook#24]
Since we talk about finding user needs, an obvious question is if we could not just ask them what they want and just build it. But this may not be a good idea.

- When we talk about finding user needs, an obvious question _**(Why is that question obvious?)**_ is: Can´t we ask them what they want and then build it? This may not be a good idea.

Usually, people want a better version of what they already have. 

- Is that really what you want to say? I have the impression, it makes sense to extend it to more than just one sentence: "When asked, people think of how they currently solve their problem, the tool, the method they use but do not talk about the underlying problem they are trying to solve."

Henry Ford allegedly said »If I had asked people what they wanted, they would have said faster horses«. Instead of faster horses, Ford sold a product that satisfied an underlying motivation – getting quickly from A to B – instead of the specific wish.

Getting to know about the underlying motivation (why do they want to get from A to B?), the activities (How do they currently get from A to B) and their problems (What is currently unpleasant about getting from A to B) is what helps us to understand users better.

This does not mean that what people wish can or should be ignored or that some ingenious designer is needed to show them their true needs. I just want to say that asking for needs directly and than just building it is not as simple and helpful as it seems intuitively.

- "It doesn´t mean that what people wish, can or should be ignored..."
- "What I want to say is, that asking for needs directly and building solutions based on those findings, is not as simple and helpful as intuition might suggest."

**Comment by jdittrich** [comment]
> When we talk about finding user needs, an obvious question  (Why is that question obvious?)

I don't know, but it seems that roughly 90% of people I tell that I talk with users of our software (and also after more elaborate explanations) assume that I ask them what they want.

But I can easily leave the "obvious" out and leave the obviousness up to the reader.

**Comment by jdittrich** [comment]
I reworked the section and close this
